// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface FailMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.FailMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
