// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface FileMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.FileMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文件名
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 文件名
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
