// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

/**
 * Protobuf type {@code com.asura.rpc.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.asura.rpc.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    dataType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            dataType_ = rawValue;
            break;
          }
          case 18: {
            com.asura.proto.Response.Builder subBuilder = null;
            if (dataBodyCase_ == 2) {
              subBuilder = ((com.asura.proto.Response) dataBody_).toBuilder();
            }
            dataBody_ =
                input.readMessage(com.asura.proto.Response.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.Response) dataBody_);
              dataBody_ = subBuilder.buildPartial();
            }
            dataBodyCase_ = 2;
            break;
          }
          case 26: {
            com.asura.proto.Request.Builder subBuilder = null;
            if (dataBodyCase_ == 3) {
              subBuilder = ((com.asura.proto.Request) dataBody_).toBuilder();
            }
            dataBody_ =
                input.readMessage(com.asura.proto.Request.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.Request) dataBody_);
              dataBody_ = subBuilder.buildPartial();
            }
            dataBodyCase_ = 3;
            break;
          }
          case 32: {

            time_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.asura.proto.Message.class, com.asura.proto.Message.Builder.class);
  }

  /**
   * Protobuf enum {@code com.asura.rpc.Message.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>requestType = 0;</code>
     */
    requestType(0),
    /**
     * <code>responseType = 1;</code>
     */
    responseType(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>requestType = 0;</code>
     */
    public static final int requestType_VALUE = 0;
    /**
     * <code>responseType = 1;</code>
     */
    public static final int responseType_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return requestType;
        case 1: return responseType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.asura.proto.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.asura.rpc.Message.DataType)
  }

  private int dataBodyCase_ = 0;
  private java.lang.Object dataBody_;
  public enum DataBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RESPONSE(2),
    REQUEST(3),
    DATABODY_NOT_SET(0);
    private final int value;
    private DataBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataBodyCase forNumber(int value) {
      switch (value) {
        case 2: return RESPONSE;
        case 3: return REQUEST;
        case 0: return DATABODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataBodyCase
  getDataBodyCase() {
    return DataBodyCase.forNumber(
        dataBodyCase_);
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 1;
  private int dataType_;
  /**
   * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  @java.lang.Override public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
   * @return The dataType.
   */
  @java.lang.Override public com.asura.proto.Message.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.asura.proto.Message.DataType result = com.asura.proto.Message.DataType.valueOf(dataType_);
    return result == null ? com.asura.proto.Message.DataType.UNRECOGNIZED : result;
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return dataBodyCase_ == 2;
  }
  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   * @return The response.
   */
  @java.lang.Override
  public com.asura.proto.Response getResponse() {
    if (dataBodyCase_ == 2) {
       return (com.asura.proto.Response) dataBody_;
    }
    return com.asura.proto.Response.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   */
  @java.lang.Override
  public com.asura.proto.ResponseOrBuilder getResponseOrBuilder() {
    if (dataBodyCase_ == 2) {
       return (com.asura.proto.Response) dataBody_;
    }
    return com.asura.proto.Response.getDefaultInstance();
  }

  public static final int REQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   * @return Whether the request field is set.
   */
  @java.lang.Override
  public boolean hasRequest() {
    return dataBodyCase_ == 3;
  }
  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   * @return The request.
   */
  @java.lang.Override
  public com.asura.proto.Request getRequest() {
    if (dataBodyCase_ == 3) {
       return (com.asura.proto.Request) dataBody_;
    }
    return com.asura.proto.Request.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   */
  @java.lang.Override
  public com.asura.proto.RequestOrBuilder getRequestOrBuilder() {
    if (dataBodyCase_ == 3) {
       return (com.asura.proto.Request) dataBody_;
    }
    return com.asura.proto.Request.getDefaultInstance();
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private long time_;
  /**
   * <code>uint64 time = 4;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataType_ != com.asura.proto.Message.DataType.requestType.getNumber()) {
      output.writeEnum(1, dataType_);
    }
    if (dataBodyCase_ == 2) {
      output.writeMessage(2, (com.asura.proto.Response) dataBody_);
    }
    if (dataBodyCase_ == 3) {
      output.writeMessage(3, (com.asura.proto.Request) dataBody_);
    }
    if (time_ != 0L) {
      output.writeUInt64(4, time_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataType_ != com.asura.proto.Message.DataType.requestType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataType_);
    }
    if (dataBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.asura.proto.Response) dataBody_);
    }
    if (dataBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.asura.proto.Request) dataBody_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, time_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.asura.proto.Message)) {
      return super.equals(obj);
    }
    com.asura.proto.Message other = (com.asura.proto.Message) obj;

    if (dataType_ != other.dataType_) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
    switch (dataBodyCase_) {
      case 2:
        if (!getResponse()
            .equals(other.getResponse())) return false;
        break;
      case 3:
        if (!getRequest()
            .equals(other.getRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    switch (dataBodyCase_) {
      case 2:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.asura.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.asura.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.asura.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.asura.rpc.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.asura.rpc.Message)
      com.asura.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.asura.proto.Message.class, com.asura.proto.Message.Builder.class);
    }

    // Construct using com.asura.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataType_ = 0;

      time_ = 0L;

      dataBodyCase_ = 0;
      dataBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Message_descriptor;
    }

    @java.lang.Override
    public com.asura.proto.Message getDefaultInstanceForType() {
      return com.asura.proto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.asura.proto.Message build() {
      com.asura.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.asura.proto.Message buildPartial() {
      com.asura.proto.Message result = new com.asura.proto.Message(this);
      result.dataType_ = dataType_;
      if (dataBodyCase_ == 2) {
        if (responseBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = responseBuilder_.build();
        }
      }
      if (dataBodyCase_ == 3) {
        if (requestBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = requestBuilder_.build();
        }
      }
      result.time_ = time_;
      result.dataBodyCase_ = dataBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.asura.proto.Message) {
        return mergeFrom((com.asura.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.asura.proto.Message other) {
      if (other == com.asura.proto.Message.getDefaultInstance()) return this;
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      switch (other.getDataBodyCase()) {
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case REQUEST: {
          mergeRequest(other.getRequest());
          break;
        }
        case DATABODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.asura.proto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.asura.proto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public DataBodyCase
        getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public Builder clearDataBody() {
      dataBodyCase_ = 0;
      dataBody_ = null;
      onChanged();
      return this;
    }


    private int dataType_ = 0;
    /**
     * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
     * @param value The enum numeric value on the wire for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeValue(int value) {

      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override
    public com.asura.proto.Message.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.asura.proto.Message.DataType result = com.asura.proto.Message.DataType.valueOf(dataType_);
      return result == null ? com.asura.proto.Message.DataType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(com.asura.proto.Message.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {

      dataType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.Response, com.asura.proto.Response.Builder, com.asura.proto.ResponseOrBuilder> responseBuilder_;
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.asura.proto.Response getResponse() {
      if (responseBuilder_ == null) {
        if (dataBodyCase_ == 2) {
          return (com.asura.proto.Response) dataBody_;
        }
        return com.asura.proto.Response.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 2) {
          return responseBuilder_.getMessage();
        }
        return com.asura.proto.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    public Builder setResponse(com.asura.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    public Builder setResponse(
        com.asura.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    public Builder mergeResponse(com.asura.proto.Response value) {
      if (responseBuilder_ == null) {
        if (dataBodyCase_ == 2 &&
            dataBody_ != com.asura.proto.Response.getDefaultInstance()) {
          dataBody_ = com.asura.proto.Response.newBuilder((com.asura.proto.Response) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 2) {
          responseBuilder_.mergeFrom(value);
        }
        responseBuilder_.setMessage(value);
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (dataBodyCase_ == 2) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 2) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    public com.asura.proto.Response.Builder getResponseBuilder() {
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    @java.lang.Override
    public com.asura.proto.ResponseOrBuilder getResponseOrBuilder() {
      if ((dataBodyCase_ == 2) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 2) {
          return (com.asura.proto.Response) dataBody_;
        }
        return com.asura.proto.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.Response response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.Response, com.asura.proto.Response.Builder, com.asura.proto.ResponseOrBuilder>
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(dataBodyCase_ == 2)) {
          dataBody_ = com.asura.proto.Response.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.Response, com.asura.proto.Response.Builder, com.asura.proto.ResponseOrBuilder>(
                (com.asura.proto.Response) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 2;
      onChanged();;
      return responseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.Request, com.asura.proto.Request.Builder, com.asura.proto.RequestOrBuilder> requestBuilder_;
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     * @return The request.
     */
    @java.lang.Override
    public com.asura.proto.Request getRequest() {
      if (requestBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          return (com.asura.proto.Request) dataBody_;
        }
        return com.asura.proto.Request.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 3) {
          return requestBuilder_.getMessage();
        }
        return com.asura.proto.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    public Builder setRequest(com.asura.proto.Request value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    public Builder setRequest(
        com.asura.proto.Request.Builder builderForValue) {
      if (requestBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    public Builder mergeRequest(com.asura.proto.Request value) {
      if (requestBuilder_ == null) {
        if (dataBodyCase_ == 3 &&
            dataBody_ != com.asura.proto.Request.getDefaultInstance()) {
          dataBody_ = com.asura.proto.Request.newBuilder((com.asura.proto.Request) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 3) {
          requestBuilder_.mergeFrom(value);
        }
        requestBuilder_.setMessage(value);
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        requestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    public com.asura.proto.Request.Builder getRequestBuilder() {
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    @java.lang.Override
    public com.asura.proto.RequestOrBuilder getRequestOrBuilder() {
      if ((dataBodyCase_ == 3) && (requestBuilder_ != null)) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 3) {
          return (com.asura.proto.Request) dataBody_;
        }
        return com.asura.proto.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.Request request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.Request, com.asura.proto.Request.Builder, com.asura.proto.RequestOrBuilder>
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        if (!(dataBodyCase_ == 3)) {
          dataBody_ = com.asura.proto.Request.getDefaultInstance();
        }
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.Request, com.asura.proto.Request.Builder, com.asura.proto.RequestOrBuilder>(
                (com.asura.proto.Request) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 3;
      onChanged();;
      return requestBuilder_;
    }

    private long time_ ;
    /**
     * <code>uint64 time = 4;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>uint64 time = 4;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {

      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {

      time_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.asura.rpc.Message)
  }

  // @@protoc_insertion_point(class_scope:com.asura.rpc.Message)
  private static final com.asura.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.asura.proto.Message();
  }

  public static com.asura.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.asura.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

