// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  int getDataTypeValue();
  /**
   * <code>.com.asura.rpc.Message.DataType data_type = 1;</code>
   * @return The dataType.
   */
  com.asura.proto.Message.DataType getDataType();

  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   * @return The response.
   */
  com.asura.proto.Response getResponse();
  /**
   * <code>.com.asura.rpc.Response response = 2;</code>
   */
  com.asura.proto.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   * @return The request.
   */
  com.asura.proto.Request getRequest();
  /**
   * <code>.com.asura.rpc.Request request = 3;</code>
   */
  com.asura.proto.RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>uint64 time = 4;</code>
   * @return The time.
   */
  long getTime();

  public com.asura.proto.Message.DataBodyCase getDataBodyCase();
}
