// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

/**
 * Protobuf type {@code com.asura.rpc.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.asura.rpc.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    ip_ = "";
    requestType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 24: {

            port_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            requestType_ = rawValue;
            break;
          }
          case 42: {
            com.asura.proto.FileMessage.Builder subBuilder = null;
            if (messageBodyCase_ == 5) {
              subBuilder = ((com.asura.proto.FileMessage) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.FileMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.FileMessage) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 5;
            break;
          }
          case 50: {
            com.asura.proto.OneWayMessage.Builder subBuilder = null;
            if (messageBodyCase_ == 6) {
              subBuilder = ((com.asura.proto.OneWayMessage) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.OneWayMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.OneWayMessage) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 6;
            break;
          }
          case 58: {
            com.asura.proto.RpcRequest.Builder subBuilder = null;
            if (messageBodyCase_ == 7) {
              subBuilder = ((com.asura.proto.RpcRequest) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.RpcRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.RpcRequest) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.asura.proto.Request.class, com.asura.proto.Request.Builder.class);
  }

  /**
   * Protobuf enum {@code com.asura.rpc.Request.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>fileType = 0;</code>
     */
    fileType(0),
    /**
     * <code>oneWayType = 1;</code>
     */
    oneWayType(1),
    /**
     * <code>rpcType = 2;</code>
     */
    rpcType(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>fileType = 0;</code>
     */
    public static final int fileType_VALUE = 0;
    /**
     * <code>oneWayType = 1;</code>
     */
    public static final int oneWayType_VALUE = 1;
    /**
     * <code>rpcType = 2;</code>
     */
    public static final int rpcType_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return fileType;
        case 1: return oneWayType;
        case 2: return rpcType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.asura.proto.Request.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.asura.rpc.Request.RequestType)
  }

  private int messageBodyCase_ = 0;
  private java.lang.Object messageBody_;
  public enum MessageBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE(5),
    ONEWAY(6),
    RPCREQUEST(7),
    MESSAGEBODY_NOT_SET(0);
    private final int value;
    private MessageBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageBodyCase forNumber(int value) {
      switch (value) {
        case 5: return FILE;
        case 6: return ONEWAY;
        case 7: return RPCREQUEST;
        case 0: return MESSAGEBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageBodyCase
  getMessageBodyCase() {
    return MessageBodyCase.forNumber(
        messageBodyCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int IP_FIELD_NUMBER = 2;
  private volatile java.lang.Object ip_;
  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  @java.lang.Override
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 3;
  private int port_;
  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  @java.lang.Override
  public int getPort() {
    return port_;
  }

  public static final int REQUEST_TYPE_FIELD_NUMBER = 4;
  private int requestType_;
  /**
   * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  @java.lang.Override public int getRequestTypeValue() {
    return requestType_;
  }
  /**
   * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
   * @return The requestType.
   */
  @java.lang.Override public com.asura.proto.Request.RequestType getRequestType() {
    @SuppressWarnings("deprecation")
    com.asura.proto.Request.RequestType result = com.asura.proto.Request.RequestType.valueOf(requestType_);
    return result == null ? com.asura.proto.Request.RequestType.UNRECOGNIZED : result;
  }

  public static final int FILE_FIELD_NUMBER = 5;
  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return messageBodyCase_ == 5;
  }
  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   * @return The file.
   */
  @java.lang.Override
  public com.asura.proto.FileMessage getFile() {
    if (messageBodyCase_ == 5) {
       return (com.asura.proto.FileMessage) messageBody_;
    }
    return com.asura.proto.FileMessage.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   */
  @java.lang.Override
  public com.asura.proto.FileMessageOrBuilder getFileOrBuilder() {
    if (messageBodyCase_ == 5) {
       return (com.asura.proto.FileMessage) messageBody_;
    }
    return com.asura.proto.FileMessage.getDefaultInstance();
  }

  public static final int ONEWAY_FIELD_NUMBER = 6;
  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   * @return Whether the oneWay field is set.
   */
  @java.lang.Override
  public boolean hasOneWay() {
    return messageBodyCase_ == 6;
  }
  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   * @return The oneWay.
   */
  @java.lang.Override
  public com.asura.proto.OneWayMessage getOneWay() {
    if (messageBodyCase_ == 6) {
       return (com.asura.proto.OneWayMessage) messageBody_;
    }
    return com.asura.proto.OneWayMessage.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   */
  @java.lang.Override
  public com.asura.proto.OneWayMessageOrBuilder getOneWayOrBuilder() {
    if (messageBodyCase_ == 6) {
       return (com.asura.proto.OneWayMessage) messageBody_;
    }
    return com.asura.proto.OneWayMessage.getDefaultInstance();
  }

  public static final int RPCREQUEST_FIELD_NUMBER = 7;
  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   * @return Whether the rpcRequest field is set.
   */
  @java.lang.Override
  public boolean hasRpcRequest() {
    return messageBodyCase_ == 7;
  }
  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   * @return The rpcRequest.
   */
  @java.lang.Override
  public com.asura.proto.RpcRequest getRpcRequest() {
    if (messageBodyCase_ == 7) {
       return (com.asura.proto.RpcRequest) messageBody_;
    }
    return com.asura.proto.RpcRequest.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   */
  @java.lang.Override
  public com.asura.proto.RpcRequestOrBuilder getRpcRequestOrBuilder() {
    if (messageBodyCase_ == 7) {
       return (com.asura.proto.RpcRequest) messageBody_;
    }
    return com.asura.proto.RpcRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
    }
    if (port_ != 0) {
      output.writeInt32(3, port_);
    }
    if (requestType_ != com.asura.proto.Request.RequestType.fileType.getNumber()) {
      output.writeEnum(4, requestType_);
    }
    if (messageBodyCase_ == 5) {
      output.writeMessage(5, (com.asura.proto.FileMessage) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      output.writeMessage(6, (com.asura.proto.OneWayMessage) messageBody_);
    }
    if (messageBodyCase_ == 7) {
      output.writeMessage(7, (com.asura.proto.RpcRequest) messageBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, port_);
    }
    if (requestType_ != com.asura.proto.Request.RequestType.fileType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, requestType_);
    }
    if (messageBodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.asura.proto.FileMessage) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.asura.proto.OneWayMessage) messageBody_);
    }
    if (messageBodyCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.asura.proto.RpcRequest) messageBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.asura.proto.Request)) {
      return super.equals(obj);
    }
    com.asura.proto.Request other = (com.asura.proto.Request) obj;

    if (getId()
        != other.getId()) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (requestType_ != other.requestType_) return false;
    if (!getMessageBodyCase().equals(other.getMessageBodyCase())) return false;
    switch (messageBodyCase_) {
      case 5:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 6:
        if (!getOneWay()
            .equals(other.getOneWay())) return false;
        break;
      case 7:
        if (!getRpcRequest()
            .equals(other.getRpcRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + requestType_;
    switch (messageBodyCase_) {
      case 5:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ONEWAY_FIELD_NUMBER;
        hash = (53 * hash) + getOneWay().hashCode();
        break;
      case 7:
        hash = (37 * hash) + RPCREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRpcRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.asura.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.asura.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.asura.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.asura.rpc.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.asura.rpc.Request)
      com.asura.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.asura.proto.Request.class, com.asura.proto.Request.Builder.class);
    }

    // Construct using com.asura.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      ip_ = "";

      port_ = 0;

      requestType_ = 0;

      messageBodyCase_ = 0;
      messageBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Request_descriptor;
    }

    @java.lang.Override
    public com.asura.proto.Request getDefaultInstanceForType() {
      return com.asura.proto.Request.getDefaultInstance();
    }

    @java.lang.Override
    public com.asura.proto.Request build() {
      com.asura.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.asura.proto.Request buildPartial() {
      com.asura.proto.Request result = new com.asura.proto.Request(this);
      result.id_ = id_;
      result.ip_ = ip_;
      result.port_ = port_;
      result.requestType_ = requestType_;
      if (messageBodyCase_ == 5) {
        if (fileBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = fileBuilder_.build();
        }
      }
      if (messageBodyCase_ == 6) {
        if (oneWayBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = oneWayBuilder_.build();
        }
      }
      if (messageBodyCase_ == 7) {
        if (rpcRequestBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = rpcRequestBuilder_.build();
        }
      }
      result.messageBodyCase_ = messageBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.asura.proto.Request) {
        return mergeFrom((com.asura.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.asura.proto.Request other) {
      if (other == com.asura.proto.Request.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.requestType_ != 0) {
        setRequestTypeValue(other.getRequestTypeValue());
      }
      switch (other.getMessageBodyCase()) {
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case ONEWAY: {
          mergeOneWay(other.getOneWay());
          break;
        }
        case RPCREQUEST: {
          mergeRpcRequest(other.getRpcRequest());
          break;
        }
        case MESSAGEBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.asura.proto.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.asura.proto.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int messageBodyCase_ = 0;
    private java.lang.Object messageBody_;
    public MessageBodyCase
        getMessageBodyCase() {
      return MessageBodyCase.forNumber(
          messageBodyCase_);
    }

    public Builder clearMessageBody() {
      messageBodyCase_ = 0;
      messageBody_ = null;
      onChanged();
      return this;
    }


    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {

      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 2;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {

      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 2;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      ip_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 3;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {

      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {

      port_ = 0;
      onChanged();
      return this;
    }

    private int requestType_ = 0;
    /**
     * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
     * @param value The enum numeric value on the wire for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeValue(int value) {

      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
     * @return The requestType.
     */
    @java.lang.Override
    public com.asura.proto.Request.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      com.asura.proto.Request.RequestType result = com.asura.proto.Request.RequestType.valueOf(requestType_);
      return result == null ? com.asura.proto.Request.RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(com.asura.proto.Request.RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      requestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {

      requestType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.FileMessage, com.asura.proto.FileMessage.Builder, com.asura.proto.FileMessageOrBuilder> fileBuilder_;
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return messageBodyCase_ == 5;
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     * @return The file.
     */
    @java.lang.Override
    public com.asura.proto.FileMessage getFile() {
      if (fileBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          return (com.asura.proto.FileMessage) messageBody_;
        }
        return com.asura.proto.FileMessage.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 5) {
          return fileBuilder_.getMessage();
        }
        return com.asura.proto.FileMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    public Builder setFile(com.asura.proto.FileMessage value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    public Builder setFile(
        com.asura.proto.FileMessage.Builder builderForValue) {
      if (fileBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    public Builder mergeFile(com.asura.proto.FileMessage value) {
      if (fileBuilder_ == null) {
        if (messageBodyCase_ == 5 &&
            messageBody_ != com.asura.proto.FileMessage.getDefaultInstance()) {
          messageBody_ = com.asura.proto.FileMessage.newBuilder((com.asura.proto.FileMessage) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 5) {
          fileBuilder_.mergeFrom(value);
        }
        fileBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    public com.asura.proto.FileMessage.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    @java.lang.Override
    public com.asura.proto.FileMessageOrBuilder getFileOrBuilder() {
      if ((messageBodyCase_ == 5) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 5) {
          return (com.asura.proto.FileMessage) messageBody_;
        }
        return com.asura.proto.FileMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.FileMessage file = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.FileMessage, com.asura.proto.FileMessage.Builder, com.asura.proto.FileMessageOrBuilder>
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(messageBodyCase_ == 5)) {
          messageBody_ = com.asura.proto.FileMessage.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.FileMessage, com.asura.proto.FileMessage.Builder, com.asura.proto.FileMessageOrBuilder>(
                (com.asura.proto.FileMessage) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 5;
      onChanged();;
      return fileBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.OneWayMessage, com.asura.proto.OneWayMessage.Builder, com.asura.proto.OneWayMessageOrBuilder> oneWayBuilder_;
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     * @return Whether the oneWay field is set.
     */
    @java.lang.Override
    public boolean hasOneWay() {
      return messageBodyCase_ == 6;
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     * @return The oneWay.
     */
    @java.lang.Override
    public com.asura.proto.OneWayMessage getOneWay() {
      if (oneWayBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          return (com.asura.proto.OneWayMessage) messageBody_;
        }
        return com.asura.proto.OneWayMessage.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 6) {
          return oneWayBuilder_.getMessage();
        }
        return com.asura.proto.OneWayMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    public Builder setOneWay(com.asura.proto.OneWayMessage value) {
      if (oneWayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        oneWayBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    public Builder setOneWay(
        com.asura.proto.OneWayMessage.Builder builderForValue) {
      if (oneWayBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        oneWayBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    public Builder mergeOneWay(com.asura.proto.OneWayMessage value) {
      if (oneWayBuilder_ == null) {
        if (messageBodyCase_ == 6 &&
            messageBody_ != com.asura.proto.OneWayMessage.getDefaultInstance()) {
          messageBody_ = com.asura.proto.OneWayMessage.newBuilder((com.asura.proto.OneWayMessage) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 6) {
          oneWayBuilder_.mergeFrom(value);
        }
        oneWayBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    public Builder clearOneWay() {
      if (oneWayBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        oneWayBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    public com.asura.proto.OneWayMessage.Builder getOneWayBuilder() {
      return getOneWayFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    @java.lang.Override
    public com.asura.proto.OneWayMessageOrBuilder getOneWayOrBuilder() {
      if ((messageBodyCase_ == 6) && (oneWayBuilder_ != null)) {
        return oneWayBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 6) {
          return (com.asura.proto.OneWayMessage) messageBody_;
        }
        return com.asura.proto.OneWayMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.OneWayMessage, com.asura.proto.OneWayMessage.Builder, com.asura.proto.OneWayMessageOrBuilder>
        getOneWayFieldBuilder() {
      if (oneWayBuilder_ == null) {
        if (!(messageBodyCase_ == 6)) {
          messageBody_ = com.asura.proto.OneWayMessage.getDefaultInstance();
        }
        oneWayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.OneWayMessage, com.asura.proto.OneWayMessage.Builder, com.asura.proto.OneWayMessageOrBuilder>(
                (com.asura.proto.OneWayMessage) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 6;
      onChanged();;
      return oneWayBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.RpcRequest, com.asura.proto.RpcRequest.Builder, com.asura.proto.RpcRequestOrBuilder> rpcRequestBuilder_;
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     * @return Whether the rpcRequest field is set.
     */
    @java.lang.Override
    public boolean hasRpcRequest() {
      return messageBodyCase_ == 7;
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     * @return The rpcRequest.
     */
    @java.lang.Override
    public com.asura.proto.RpcRequest getRpcRequest() {
      if (rpcRequestBuilder_ == null) {
        if (messageBodyCase_ == 7) {
          return (com.asura.proto.RpcRequest) messageBody_;
        }
        return com.asura.proto.RpcRequest.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 7) {
          return rpcRequestBuilder_.getMessage();
        }
        return com.asura.proto.RpcRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    public Builder setRpcRequest(com.asura.proto.RpcRequest value) {
      if (rpcRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        rpcRequestBuilder_.setMessage(value);
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    public Builder setRpcRequest(
        com.asura.proto.RpcRequest.Builder builderForValue) {
      if (rpcRequestBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        rpcRequestBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    public Builder mergeRpcRequest(com.asura.proto.RpcRequest value) {
      if (rpcRequestBuilder_ == null) {
        if (messageBodyCase_ == 7 &&
            messageBody_ != com.asura.proto.RpcRequest.getDefaultInstance()) {
          messageBody_ = com.asura.proto.RpcRequest.newBuilder((com.asura.proto.RpcRequest) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 7) {
          rpcRequestBuilder_.mergeFrom(value);
        }
        rpcRequestBuilder_.setMessage(value);
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    public Builder clearRpcRequest() {
      if (rpcRequestBuilder_ == null) {
        if (messageBodyCase_ == 7) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 7) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        rpcRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    public com.asura.proto.RpcRequest.Builder getRpcRequestBuilder() {
      return getRpcRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    @java.lang.Override
    public com.asura.proto.RpcRequestOrBuilder getRpcRequestOrBuilder() {
      if ((messageBodyCase_ == 7) && (rpcRequestBuilder_ != null)) {
        return rpcRequestBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 7) {
          return (com.asura.proto.RpcRequest) messageBody_;
        }
        return com.asura.proto.RpcRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.RpcRequest, com.asura.proto.RpcRequest.Builder, com.asura.proto.RpcRequestOrBuilder>
        getRpcRequestFieldBuilder() {
      if (rpcRequestBuilder_ == null) {
        if (!(messageBodyCase_ == 7)) {
          messageBody_ = com.asura.proto.RpcRequest.getDefaultInstance();
        }
        rpcRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.RpcRequest, com.asura.proto.RpcRequest.Builder, com.asura.proto.RpcRequestOrBuilder>(
                (com.asura.proto.RpcRequest) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 7;
      onChanged();;
      return rpcRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.asura.rpc.Request)
  }

  // @@protoc_insertion_point(class_scope:com.asura.rpc.Request)
  private static final com.asura.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.asura.proto.Request();
  }

  public static com.asura.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.asura.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

