// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <code>.com.asura.rpc.Request.RequestType request_type = 4;</code>
   * @return The requestType.
   */
  com.asura.proto.Request.RequestType getRequestType();

  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   * @return The file.
   */
  com.asura.proto.FileMessage getFile();
  /**
   * <code>.com.asura.rpc.FileMessage file = 5;</code>
   */
  com.asura.proto.FileMessageOrBuilder getFileOrBuilder();

  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   * @return Whether the oneWay field is set.
   */
  boolean hasOneWay();
  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   * @return The oneWay.
   */
  com.asura.proto.OneWayMessage getOneWay();
  /**
   * <code>.com.asura.rpc.OneWayMessage oneWay = 6;</code>
   */
  com.asura.proto.OneWayMessageOrBuilder getOneWayOrBuilder();

  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   * @return Whether the rpcRequest field is set.
   */
  boolean hasRpcRequest();
  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   * @return The rpcRequest.
   */
  com.asura.proto.RpcRequest getRpcRequest();
  /**
   * <code>.com.asura.rpc.RpcRequest rpcRequest = 7;</code>
   */
  com.asura.proto.RpcRequestOrBuilder getRpcRequestOrBuilder();

  public com.asura.proto.Request.MessageBodyCase getMessageBodyCase();
}
