// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

/**
 * Protobuf type {@code com.asura.rpc.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.asura.rpc.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    responseType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            responseType_ = rawValue;
            break;
          }
          case 18: {
            com.asura.proto.SuccessMessage.Builder subBuilder = null;
            if (messageBodyCase_ == 2) {
              subBuilder = ((com.asura.proto.SuccessMessage) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.SuccessMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.SuccessMessage) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 2;
            break;
          }
          case 26: {
            com.asura.proto.FailMessage.Builder subBuilder = null;
            if (messageBodyCase_ == 3) {
              subBuilder = ((com.asura.proto.FailMessage) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.FailMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.FailMessage) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 3;
            break;
          }
          case 34: {
            com.asura.proto.RpcResponse.Builder subBuilder = null;
            if (messageBodyCase_ == 4) {
              subBuilder = ((com.asura.proto.RpcResponse) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.asura.proto.RpcResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.asura.proto.RpcResponse) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.asura.proto.Response.class, com.asura.proto.Response.Builder.class);
  }

  /**
   * Protobuf enum {@code com.asura.rpc.Response.ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>successType = 0;</code>
     */
    successType(0),
    /**
     * <code>failType = 1;</code>
     */
    failType(1),
    /**
     * <code>rpcType = 2;</code>
     */
    rpcType(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>successType = 0;</code>
     */
    public static final int successType_VALUE = 0;
    /**
     * <code>failType = 1;</code>
     */
    public static final int failType_VALUE = 1;
    /**
     * <code>rpcType = 2;</code>
     */
    public static final int rpcType_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return successType;
        case 1: return failType;
        case 2: return rpcType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.asura.proto.Response.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.asura.rpc.Response.ResponseType)
  }

  private int messageBodyCase_ = 0;
  private java.lang.Object messageBody_;
  public enum MessageBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SUCCESS(2),
    FAIL(3),
    RPCRESPONSE(4),
    MESSAGEBODY_NOT_SET(0);
    private final int value;
    private MessageBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageBodyCase forNumber(int value) {
      switch (value) {
        case 2: return SUCCESS;
        case 3: return FAIL;
        case 4: return RPCRESPONSE;
        case 0: return MESSAGEBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageBodyCase
  getMessageBodyCase() {
    return MessageBodyCase.forNumber(
        messageBodyCase_);
  }

  public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
  private int responseType_;
  /**
   * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
   * @return The enum numeric value on the wire for responseType.
   */
  @java.lang.Override public int getResponseTypeValue() {
    return responseType_;
  }
  /**
   * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
   * @return The responseType.
   */
  @java.lang.Override public com.asura.proto.Response.ResponseType getResponseType() {
    @SuppressWarnings("deprecation")
    com.asura.proto.Response.ResponseType result = com.asura.proto.Response.ResponseType.valueOf(responseType_);
    return result == null ? com.asura.proto.Response.ResponseType.UNRECOGNIZED : result;
  }

  public static final int SUCCESS_FIELD_NUMBER = 2;
  /**
   * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
   * @return Whether the success field is set.
   */
  @java.lang.Override
  public boolean hasSuccess() {
    return messageBodyCase_ == 2;
  }
  /**
   * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
   * @return The success.
   */
  @java.lang.Override
  public com.asura.proto.SuccessMessage getSuccess() {
    if (messageBodyCase_ == 2) {
       return (com.asura.proto.SuccessMessage) messageBody_;
    }
    return com.asura.proto.SuccessMessage.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
   */
  @java.lang.Override
  public com.asura.proto.SuccessMessageOrBuilder getSuccessOrBuilder() {
    if (messageBodyCase_ == 2) {
       return (com.asura.proto.SuccessMessage) messageBody_;
    }
    return com.asura.proto.SuccessMessage.getDefaultInstance();
  }

  public static final int FAIL_FIELD_NUMBER = 3;
  /**
   * <code>.com.asura.rpc.FailMessage fail = 3;</code>
   * @return Whether the fail field is set.
   */
  @java.lang.Override
  public boolean hasFail() {
    return messageBodyCase_ == 3;
  }
  /**
   * <code>.com.asura.rpc.FailMessage fail = 3;</code>
   * @return The fail.
   */
  @java.lang.Override
  public com.asura.proto.FailMessage getFail() {
    if (messageBodyCase_ == 3) {
       return (com.asura.proto.FailMessage) messageBody_;
    }
    return com.asura.proto.FailMessage.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.FailMessage fail = 3;</code>
   */
  @java.lang.Override
  public com.asura.proto.FailMessageOrBuilder getFailOrBuilder() {
    if (messageBodyCase_ == 3) {
       return (com.asura.proto.FailMessage) messageBody_;
    }
    return com.asura.proto.FailMessage.getDefaultInstance();
  }

  public static final int RPCRESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
   * @return Whether the rpcResponse field is set.
   */
  @java.lang.Override
  public boolean hasRpcResponse() {
    return messageBodyCase_ == 4;
  }
  /**
   * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
   * @return The rpcResponse.
   */
  @java.lang.Override
  public com.asura.proto.RpcResponse getRpcResponse() {
    if (messageBodyCase_ == 4) {
       return (com.asura.proto.RpcResponse) messageBody_;
    }
    return com.asura.proto.RpcResponse.getDefaultInstance();
  }
  /**
   * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
   */
  @java.lang.Override
  public com.asura.proto.RpcResponseOrBuilder getRpcResponseOrBuilder() {
    if (messageBodyCase_ == 4) {
       return (com.asura.proto.RpcResponse) messageBody_;
    }
    return com.asura.proto.RpcResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseType_ != com.asura.proto.Response.ResponseType.successType.getNumber()) {
      output.writeEnum(1, responseType_);
    }
    if (messageBodyCase_ == 2) {
      output.writeMessage(2, (com.asura.proto.SuccessMessage) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      output.writeMessage(3, (com.asura.proto.FailMessage) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      output.writeMessage(4, (com.asura.proto.RpcResponse) messageBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseType_ != com.asura.proto.Response.ResponseType.successType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, responseType_);
    }
    if (messageBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.asura.proto.SuccessMessage) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.asura.proto.FailMessage) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.asura.proto.RpcResponse) messageBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.asura.proto.Response)) {
      return super.equals(obj);
    }
    com.asura.proto.Response other = (com.asura.proto.Response) obj;

    if (responseType_ != other.responseType_) return false;
    if (!getMessageBodyCase().equals(other.getMessageBodyCase())) return false;
    switch (messageBodyCase_) {
      case 2:
        if (!getSuccess()
            .equals(other.getSuccess())) return false;
        break;
      case 3:
        if (!getFail()
            .equals(other.getFail())) return false;
        break;
      case 4:
        if (!getRpcResponse()
            .equals(other.getRpcResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + responseType_;
    switch (messageBodyCase_) {
      case 2:
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + getSuccess().hashCode();
        break;
      case 3:
        hash = (37 * hash) + FAIL_FIELD_NUMBER;
        hash = (53 * hash) + getFail().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RPCRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getRpcResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.asura.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.asura.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.asura.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.asura.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.asura.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.asura.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.asura.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.asura.rpc.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.asura.rpc.Response)
      com.asura.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.asura.proto.Response.class, com.asura.proto.Response.Builder.class);
    }

    // Construct using com.asura.proto.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseType_ = 0;

      messageBodyCase_ = 0;
      messageBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.asura.proto.RpcProto.internal_static_com_asura_rpc_Response_descriptor;
    }

    @java.lang.Override
    public com.asura.proto.Response getDefaultInstanceForType() {
      return com.asura.proto.Response.getDefaultInstance();
    }

    @java.lang.Override
    public com.asura.proto.Response build() {
      com.asura.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.asura.proto.Response buildPartial() {
      com.asura.proto.Response result = new com.asura.proto.Response(this);
      result.responseType_ = responseType_;
      if (messageBodyCase_ == 2) {
        if (successBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = successBuilder_.build();
        }
      }
      if (messageBodyCase_ == 3) {
        if (failBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = failBuilder_.build();
        }
      }
      if (messageBodyCase_ == 4) {
        if (rpcResponseBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = rpcResponseBuilder_.build();
        }
      }
      result.messageBodyCase_ = messageBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.asura.proto.Response) {
        return mergeFrom((com.asura.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.asura.proto.Response other) {
      if (other == com.asura.proto.Response.getDefaultInstance()) return this;
      if (other.responseType_ != 0) {
        setResponseTypeValue(other.getResponseTypeValue());
      }
      switch (other.getMessageBodyCase()) {
        case SUCCESS: {
          mergeSuccess(other.getSuccess());
          break;
        }
        case FAIL: {
          mergeFail(other.getFail());
          break;
        }
        case RPCRESPONSE: {
          mergeRpcResponse(other.getRpcResponse());
          break;
        }
        case MESSAGEBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.asura.proto.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.asura.proto.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int messageBodyCase_ = 0;
    private java.lang.Object messageBody_;
    public MessageBodyCase
        getMessageBodyCase() {
      return MessageBodyCase.forNumber(
          messageBodyCase_);
    }

    public Builder clearMessageBody() {
      messageBodyCase_ = 0;
      messageBody_ = null;
      onChanged();
      return this;
    }


    private int responseType_ = 0;
    /**
     * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
     * @return The enum numeric value on the wire for responseType.
     */
    @java.lang.Override public int getResponseTypeValue() {
      return responseType_;
    }
    /**
     * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
     * @param value The enum numeric value on the wire for responseType to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTypeValue(int value) {

      responseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
     * @return The responseType.
     */
    @java.lang.Override
    public com.asura.proto.Response.ResponseType getResponseType() {
      @SuppressWarnings("deprecation")
      com.asura.proto.Response.ResponseType result = com.asura.proto.Response.ResponseType.valueOf(responseType_);
      return result == null ? com.asura.proto.Response.ResponseType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
     * @param value The responseType to set.
     * @return This builder for chaining.
     */
    public Builder setResponseType(com.asura.proto.Response.ResponseType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      responseType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.asura.rpc.Response.ResponseType response_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseType() {

      responseType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.SuccessMessage, com.asura.proto.SuccessMessage.Builder, com.asura.proto.SuccessMessageOrBuilder> successBuilder_;
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return messageBodyCase_ == 2;
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public com.asura.proto.SuccessMessage getSuccess() {
      if (successBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          return (com.asura.proto.SuccessMessage) messageBody_;
        }
        return com.asura.proto.SuccessMessage.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 2) {
          return successBuilder_.getMessage();
        }
        return com.asura.proto.SuccessMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    public Builder setSuccess(com.asura.proto.SuccessMessage value) {
      if (successBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        successBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    public Builder setSuccess(
        com.asura.proto.SuccessMessage.Builder builderForValue) {
      if (successBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        successBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    public Builder mergeSuccess(com.asura.proto.SuccessMessage value) {
      if (successBuilder_ == null) {
        if (messageBodyCase_ == 2 &&
            messageBody_ != com.asura.proto.SuccessMessage.getDefaultInstance()) {
          messageBody_ = com.asura.proto.SuccessMessage.newBuilder((com.asura.proto.SuccessMessage) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 2) {
          successBuilder_.mergeFrom(value);
        }
        successBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    public Builder clearSuccess() {
      if (successBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        successBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    public com.asura.proto.SuccessMessage.Builder getSuccessBuilder() {
      return getSuccessFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    @java.lang.Override
    public com.asura.proto.SuccessMessageOrBuilder getSuccessOrBuilder() {
      if ((messageBodyCase_ == 2) && (successBuilder_ != null)) {
        return successBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 2) {
          return (com.asura.proto.SuccessMessage) messageBody_;
        }
        return com.asura.proto.SuccessMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.SuccessMessage success = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.SuccessMessage, com.asura.proto.SuccessMessage.Builder, com.asura.proto.SuccessMessageOrBuilder>
        getSuccessFieldBuilder() {
      if (successBuilder_ == null) {
        if (!(messageBodyCase_ == 2)) {
          messageBody_ = com.asura.proto.SuccessMessage.getDefaultInstance();
        }
        successBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.SuccessMessage, com.asura.proto.SuccessMessage.Builder, com.asura.proto.SuccessMessageOrBuilder>(
                (com.asura.proto.SuccessMessage) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 2;
      onChanged();;
      return successBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.FailMessage, com.asura.proto.FailMessage.Builder, com.asura.proto.FailMessageOrBuilder> failBuilder_;
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     * @return Whether the fail field is set.
     */
    @java.lang.Override
    public boolean hasFail() {
      return messageBodyCase_ == 3;
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     * @return The fail.
     */
    @java.lang.Override
    public com.asura.proto.FailMessage getFail() {
      if (failBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          return (com.asura.proto.FailMessage) messageBody_;
        }
        return com.asura.proto.FailMessage.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 3) {
          return failBuilder_.getMessage();
        }
        return com.asura.proto.FailMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    public Builder setFail(com.asura.proto.FailMessage value) {
      if (failBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        failBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    public Builder setFail(
        com.asura.proto.FailMessage.Builder builderForValue) {
      if (failBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        failBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    public Builder mergeFail(com.asura.proto.FailMessage value) {
      if (failBuilder_ == null) {
        if (messageBodyCase_ == 3 &&
            messageBody_ != com.asura.proto.FailMessage.getDefaultInstance()) {
          messageBody_ = com.asura.proto.FailMessage.newBuilder((com.asura.proto.FailMessage) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 3) {
          failBuilder_.mergeFrom(value);
        }
        failBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    public Builder clearFail() {
      if (failBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        failBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    public com.asura.proto.FailMessage.Builder getFailBuilder() {
      return getFailFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    @java.lang.Override
    public com.asura.proto.FailMessageOrBuilder getFailOrBuilder() {
      if ((messageBodyCase_ == 3) && (failBuilder_ != null)) {
        return failBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 3) {
          return (com.asura.proto.FailMessage) messageBody_;
        }
        return com.asura.proto.FailMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.FailMessage fail = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.FailMessage, com.asura.proto.FailMessage.Builder, com.asura.proto.FailMessageOrBuilder>
        getFailFieldBuilder() {
      if (failBuilder_ == null) {
        if (!(messageBodyCase_ == 3)) {
          messageBody_ = com.asura.proto.FailMessage.getDefaultInstance();
        }
        failBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.FailMessage, com.asura.proto.FailMessage.Builder, com.asura.proto.FailMessageOrBuilder>(
                (com.asura.proto.FailMessage) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 3;
      onChanged();;
      return failBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.RpcResponse, com.asura.proto.RpcResponse.Builder, com.asura.proto.RpcResponseOrBuilder> rpcResponseBuilder_;
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     * @return Whether the rpcResponse field is set.
     */
    @java.lang.Override
    public boolean hasRpcResponse() {
      return messageBodyCase_ == 4;
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     * @return The rpcResponse.
     */
    @java.lang.Override
    public com.asura.proto.RpcResponse getRpcResponse() {
      if (rpcResponseBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          return (com.asura.proto.RpcResponse) messageBody_;
        }
        return com.asura.proto.RpcResponse.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 4) {
          return rpcResponseBuilder_.getMessage();
        }
        return com.asura.proto.RpcResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    public Builder setRpcResponse(com.asura.proto.RpcResponse value) {
      if (rpcResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        rpcResponseBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    public Builder setRpcResponse(
        com.asura.proto.RpcResponse.Builder builderForValue) {
      if (rpcResponseBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        rpcResponseBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    public Builder mergeRpcResponse(com.asura.proto.RpcResponse value) {
      if (rpcResponseBuilder_ == null) {
        if (messageBodyCase_ == 4 &&
            messageBody_ != com.asura.proto.RpcResponse.getDefaultInstance()) {
          messageBody_ = com.asura.proto.RpcResponse.newBuilder((com.asura.proto.RpcResponse) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 4) {
          rpcResponseBuilder_.mergeFrom(value);
        }
        rpcResponseBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    public Builder clearRpcResponse() {
      if (rpcResponseBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        rpcResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    public com.asura.proto.RpcResponse.Builder getRpcResponseBuilder() {
      return getRpcResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    @java.lang.Override
    public com.asura.proto.RpcResponseOrBuilder getRpcResponseOrBuilder() {
      if ((messageBodyCase_ == 4) && (rpcResponseBuilder_ != null)) {
        return rpcResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 4) {
          return (com.asura.proto.RpcResponse) messageBody_;
        }
        return com.asura.proto.RpcResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.asura.rpc.RpcResponse rpcResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.asura.proto.RpcResponse, com.asura.proto.RpcResponse.Builder, com.asura.proto.RpcResponseOrBuilder>
        getRpcResponseFieldBuilder() {
      if (rpcResponseBuilder_ == null) {
        if (!(messageBodyCase_ == 4)) {
          messageBody_ = com.asura.proto.RpcResponse.getDefaultInstance();
        }
        rpcResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.asura.proto.RpcResponse, com.asura.proto.RpcResponse.Builder, com.asura.proto.RpcResponseOrBuilder>(
                (com.asura.proto.RpcResponse) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 4;
      onChanged();;
      return rpcResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.asura.rpc.Response)
  }

  // @@protoc_insertion_point(class_scope:com.asura.rpc.Response)
  private static final com.asura.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.asura.proto.Response();
  }

  public static com.asura.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.asura.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

