// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public final class RpcProto {
  private RpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_Message_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_Request_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_Response_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_FileMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_FileMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_OneWayMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_OneWayMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_RpcRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_SuccessMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_SuccessMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_FailMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_FailMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_asura_rpc_RpcResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_asura_rpc_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\rcom.asura.rpc\"\336\001\n\007Message\0222" +
      "\n\tdata_type\030\001 \001(\0162\037.com.asura.rpc.Messag" +
      "e.DataType\022+\n\010response\030\002 \001(\0132\027.com.asura" +
      ".rpc.ResponseH\000\022)\n\007request\030\003 \001(\0132\026.com.a" +
      "sura.rpc.RequestH\000\022\014\n\004time\030\004 \001(\004\"-\n\010Data" +
      "Type\022\017\n\013requestType\020\000\022\020\n\014responseType\020\001B" +
      "\n\n\010dataBody\"\277\002\n\007Request\022\n\n\002id\030\001 \001(\005\022\n\n\002i" +
      "p\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\0228\n\014request_type\030\004 " +
      "\001(\0162\".com.asura.rpc.Request.RequestType\022" +
      "*\n\004file\030\005 \001(\0132\032.com.asura.rpc.FileMessag" +
      "eH\000\022.\n\006oneWay\030\006 \001(\0132\034.com.asura.rpc.OneW" +
      "ayMessageH\000\022/\n\nrpcRequest\030\007 \001(\0132\031.com.as" +
      "ura.rpc.RpcRequestH\000\"8\n\013RequestType\022\014\n\010f" +
      "ileType\020\000\022\016\n\noneWayType\020\001\022\013\n\007rpcType\020\002B\r" +
      "\n\013messageBody\"\243\002\n\010Response\022;\n\rresponse_t" +
      "ype\030\001 \001(\0162$.com.asura.rpc.Response.Respo" +
      "nseType\0220\n\007success\030\002 \001(\0132\035.com.asura.rpc" +
      ".SuccessMessageH\000\022*\n\004fail\030\003 \001(\0132\032.com.as" +
      "ura.rpc.FailMessageH\000\0221\n\013rpcResponse\030\004 \001" +
      "(\0132\032.com.asura.rpc.RpcResponseH\000\":\n\014Resp" +
      "onseType\022\017\n\013successType\020\000\022\014\n\010failType\020\001\022" +
      "\013\n\007rpcType\020\002B\r\n\013messageBody\")\n\013FileMessa" +
      "ge\022\014\n\004name\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"\035\n\rOneWay" +
      "Message\022\014\n\004data\030\001 \001(\014\"\032\n\nRpcRequest\022\014\n\004d" +
      "ata\030\001 \001(\014\"\020\n\016SuccessMessage\"\036\n\013FailMessa" +
      "ge\022\017\n\007content\030\001 \001(\t\"\033\n\013RpcResponse\022\014\n\004da" +
      "ta\030\001 \001(\014B\037\n\017com.asura.protoB\010RpcProtoH\001P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_asura_rpc_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_asura_rpc_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_Message_descriptor,
        new java.lang.String[] { "DataType", "Response", "Request", "Time", "DataBody", });
    internal_static_com_asura_rpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_asura_rpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_Request_descriptor,
        new java.lang.String[] { "Id", "Ip", "Port", "RequestType", "File", "OneWay", "RpcRequest", "MessageBody", });
    internal_static_com_asura_rpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_asura_rpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_Response_descriptor,
        new java.lang.String[] { "ResponseType", "Success", "Fail", "RpcResponse", "MessageBody", });
    internal_static_com_asura_rpc_FileMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_asura_rpc_FileMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_FileMessage_descriptor,
        new java.lang.String[] { "Name", "Data", });
    internal_static_com_asura_rpc_OneWayMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_asura_rpc_OneWayMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_OneWayMessage_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_asura_rpc_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_asura_rpc_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_RpcRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_asura_rpc_SuccessMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_asura_rpc_SuccessMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_SuccessMessage_descriptor,
        new java.lang.String[] { });
    internal_static_com_asura_rpc_FailMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_asura_rpc_FailMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_FailMessage_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_com_asura_rpc_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_asura_rpc_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_asura_rpc_RpcResponse_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
