// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
