// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.asura.proto;

public interface SuccessMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.asura.rpc.SuccessMessage)
    com.google.protobuf.MessageOrBuilder {
}
